### ISSUE TITLE
Not able to find the file slack_settings

### ISSUE THREAD

**Issue by Saneesh** [acquia/cloud-hooks#44]
Hi all,
I'm not able to find slack_settings file in home directory of my server. Where can I find it and how can I set the generated TOKEN? what is the format?

Regards,
Saneesh.

**Comment by StevenGFX** [comment]
@Saneesh You can create a slack_settings file or copy and modify [/samples/slack/slack_settings](https://github.com/acquia/cloud-hooks/blob/master/samples/slack/slack_settings).  Follow the [instructions ](https://my.slack.com/services/new/incoming-webhook/) for setting up an incoming webhook integration for Slack. Then you will need to modify your slack.sh file. Line 21 of [/samples/slack/slack.sh](https://github.com/acquia/cloud-hooks/blob/master/samples/slack/slack.sh)

**Comment by blkperl** [comment]
Resolved in #43
