### ISSUE TITLE
Is it possible to setup GitHub Webhooks to trigger one of these custom hooks?

### ISSUE THREAD

**Issue by mccrodp** [acquia/cloud-hooks#46]
We are looking for a simple method of keeping our `develop` branch in sync with Acquia Cloud dev environment.

Can a GitHub Webhook trigger one of these custom Acquia hooks to clone the latest version of the repo from GitHub? Or do you have an alternate suggestion?

Thanks!

**Comment by bjaspan** [comment]
Take a look at Acquia Pipelines. It is a continuous-integration/deployment system for Acquia Cloud. Among other things, it lets you use GitHub as the source for your build that is deployed to Cloud.  If your "build process" has no steps, the net effect is just cloning your GitHub branches into Cloud for deployment.

**Comment by mccrodp** [comment]
Thanks, I was wondering if possible without Pipelines, but have since signed up to the beta program. Awaiting access now, but not sure how long it takes. Cheers.
