### ISSUE TITLE
How to read from a file inside a post-code-deploy script

### ISSUE THREAD

**Issue by steffen25** [acquia/cloud-hooks#50]
Hey I created a bash script that reads some data from a .yml file but if I place this .yml file inside the post-code-deploy folder it will try to execute the .yml file I thought the way the cloud hook works is that it will only execute files that has the executable bit set? anyway I would like to know how I can read a file inside my bash script inside the post-code-deploy folder. 

Thank you.

**Comment by rubenvarela** [comment]
I know this is old, but might as well get this documented here,

If you need the full file, 

`variable=$(cat file.yml)`

If you need it line by line,

```
count=0;
while read line; do
count=$(($count+1));
echo "Line: $count";
echo "$line";
done <file.yml
```

**Comment by steffen25** [comment]
Hey @rubenvarela Thanks for your input :) I managed to solved it.
